apiVersion: batch/v1
kind: CronJob
metadata:
  name: usgs-job
  namespace: default
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: usgs
              image: ghcr.io/cy-2004/usgs:latest
              imagePullPolicy: Always
              env:
                - name: DYNAMODB_TABLE
                  value: "usgs-data"
                - name: S3_BUCKET
                  value: "gzd2yk-ds5220-project2"
                - name: AWS_REGION
                  value: "us-east-1"